# Generated by Django 4.1.7 on 2023-03-03 18:28

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Full name')),
                ('job', models.BooleanField(blank=True, null=True, verbose_name='Job')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('domain_name', models.URLField(blank=True, null=True, verbose_name='Domain name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone number')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company name')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('integer', models.IntegerField(blank=True, null=True, verbose_name='Integer')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Date')),
            ],
        ),
    ]
