# Generated by Django 4.1.7 on 2023-03-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystical_users', '0002_alter_schema_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='job',
            field=models.BooleanField(blank=True, null=True, verbose_name='Do have a job ?'),
        ),
    ]
