# Generated by Django 4.1.7 on 2023-03-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystical_users', '0003_alter_schema_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='job',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Job'),
        ),
    ]
